### ISSUE TITLE
createObjectStore bumps db version

### ISSUE THREAD

**Issue by LukeMcDonnell** [assuncaocharles/ngx-indexed-db#242]
Everytime createObjectStore is called, the database version is incremented. Just trying to figure out if this is intended behaviour or am I doing something wrong?

I have the following config in my app.module, which is passed to the ngx-indexed-db module forRoot method:

`const dbConfig: DBConfig  = {
  name: 'appDb',
  version: 1,
  objectStoresMeta: [
  ]
};`

Which creates a new database (version 1) with no stores, which is fine. 

Then, in the user authentication service, I'm creating new object stores when a user logs in:

```
private createDataStores(): void {
    const offlineCacheSchema: ObjectStoreMeta = {
      store: 'offlineCache-' + this.user.id,
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [
        { name: 'endpoint', keypath: 'endpoint', options: { unique: false } },
        { name: 'ulid', keypath: 'ulid', options: { unique: true } },
        { name: 'data', keypath: 'data', options: { unique: false } }
      ]
    }

    const apiCacheSchema: ObjectStoreMeta = {
      store: 'apiCache-' + this.user.id,
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [
        { name: 'endpoint', keypath: 'endpoint', options: { unique: true } },
        { name: 'timestamp', keypath: 'timestamp', options: { unique: false } },
        { name: 'data', keypath: 'data', options: { unique: false } }
      ]
    };

    this.dbService.createObjectStore(offlineCacheSchema);
    this.dbService.createObjectStore(apiCacheSchema);
  }
```

The stores are created fine, but the database version bumps to 3. Reloading the app gives the following error:
![image](https://user-images.githubusercontent.com/15354254/117779050-70ea6e00-b27d-11eb-9090-c2eec326066f.png)

![image](https://user-images.githubusercontent.com/15354254/117779362-c45cbc00-b27d-11eb-80a5-d2d265a48313.png)

![image](https://user-images.githubusercontent.com/15354254/117779891-41883100-b27e-11eb-8fd7-acbc3782b0ac.png)

Since version is a required property, and the module requires DbConfig. I'm not sure how to use createObjectStore to create dynamic stores if the version increments every time.

**Comment by assuncaocharles** [comment]
Hi @LukeMcDonnell 

Can you create a codesandbox reproducing it?

**Comment by LukeMcDonnell** [comment]
Yup, here ya go.
https://codesandbox.io/s/trusting-glade-7dwm3

**Comment by assuncaocharles** [comment]
Hey @LukeMcDonnell 

I figure what is happening and yes, we bump the version on purpose, it happens here:

https://github.com/assuncaocharles/ngx-indexed-db/blob/6b5eb28559cd2c518e74491da79a94dc74f01a24/projects/ngx-indexed-db/src/lib/ngx-indexed-db.service.ts#L48

This is because it's intent to be called once, on DB initialization when you do the `forRoot()` call, here:

https://github.com/assuncaocharles/ngx-indexed-db/blob/6b5eb28559cd2c518e74491da79a94dc74f01a24/projects/ngx-indexed-db/src/lib/ngx-indexed-db.service.ts#L28-L34

What you are missing in your code is the storeDefinitions in you `dbConfig` like in [this CodeSandbox](https://codesandbox.io/s/floral-thunder-thbnf?file=/src/app/app.module.ts)


Let me know if that clarifies all your questions

**Comment by LukeMcDonnell** [comment]
Hi @assuncaocharles 

Yes, that seems right, and adding the storeDefinitions in the dbConfig does work, as in the examples.

So what is the use-case of exposing createObjectStore in the service? The docs indicate it should allow creating ad-hoc data stores, but this isn't possible if the db version increments each time a new store is created.
![image](https://user-images.githubusercontent.com/15354254/117895511-a5057380-b2fd-11eb-919b-e6efec914044.png)

**Comment by assuncaocharles** [comment]
Hey @LukeMcDonnell 

Considering you already have the db created ( That it is what happens in the when you call it in the module declaration ), you have the option to add a new store if you need to but the catch is that the only way to update a DB, meaning adding the new store, is by bumping the version, therefore the behavior you were facing is same if you would be:

1. Creating the DB with no stores
2. Updating the DB to have X store ( Bumping to new version )
3. Updating the DB again to have Y store ( Bumping again )

I do say that is expected behavior.

**Comment by assuncaocharles** [comment]
HI @LukeMcDonnell 

I am closing this one since looks like you have no more questions, feel free to reopen if you still need any help.

**Comment by LukeMcDonnell** [comment]
Hi @assuncaocharles 

> 1 Creating the DB with no stores
2 Updating the DB to have X store ( Bumping to new version )
3 Updating the DB again to have Y store ( Bumping again )

Maybe I'm missing something here? In step 1 we need to define a database version in the `DBConfig` passed to the module forRoot() config. AFAICT, there's no way to import the module without passing a DBConfig with a db version number in the module declaration, is that right? 

If so, I can't see how it's possible to use createObjectStore to create ad-hoc databases without breaking the module next time the app initialises, since the versions will never match.

**Comment by assuncaocharles** [comment]
That is a good catch for the lib to handler in the future, for now I would say the consumer will have to handle the dbVersion control. Here is a example of workaround https://codesandbox.io/s/floral-thunder-thbnf?file=/src/app/app.component.ts

**Comment by 0xrgg** [comment]
> That is a good catch for the lib to handler in the future, for now I would say the consumer will have to handle the dbVersion control. Here is a example of workaround https://codesandbox.io/s/floral-thunder-thbnf?file=/src/app/app.component.ts

@assuncaocharles  - is this codesandbox still up? I signed in but says it's unavailable but I believe this workaround may be valuable to me
