### ISSUE TITLE
Use HttpClient inside migrationFactory

### ISSUE THREAD

**Issue by dj-fiorex** [assuncaocharles/ngx-indexed-db#262]
Hi all, thanks for this library, i need some advice on how to pass an instance of httpclient to the migrationFactory function because i need to retrieve a json to populate db.
Thanks!

**Comment by dj-fiorex** [comment]
Anyone could help me? i think this is a basic question and a common use case, when a new browser open my app i need to create the db and populate it with a json fetched from my server.
Please help!
Thanks

**Comment by aparzi** [comment]
Hi @dj-fiorex,
it is not possible to use an instance of httpclient in the migrationFactory function, because this function has the purpose of create db and perform migrations. You should first retrieve the data from server and after create and populate the db. 
If you need other clarifications or have suggestions feel free to write.

**Comment by aparzi** [comment]
Hi @assuncaocharles,
I believe this issue can be considered closed.

**Comment by aparzi** [comment]
Hi @assuncaocharles,
what do you think this issue?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
I believe this issue can be considered closed.
