### ISSUE TITLE
Insert array of data using bulkAdd

### ISSUE THREAD

**Issue by DamForums** [assuncaocharles/ngx-indexed-db#282]
I am using this package to store 200k records to indexed db.

I have created the db store like this.
`const dbConfig: DBConfig = {
  name: 'university',
  version: 1,
  objectStoresMeta: [
    {
      store: 'students',
      storeConfig: { keyPath: 'Id', autoIncrement: true },
      storeSchema: [
        { name: 'Id', keypath: 'Id', options: { unique: true} },
        { name: 'SID', keypath: 'SID', options: { unique: false } },
        { name: 'Name', keypath: 'Name', options: { unique: false } },
        { name: 'Age', keypath: 'Age', options: { unique: false }, }
      ],
    },
  ],
};`
And I have this type of array which contains 200k records.
`[
  {
    "SID": "A",
    "Name": "A",
    "Age": "A"
  },
  {
    "SID": "A",
    "Name": "A",
    "Age": "A"
  },
  {
    "SID": "A",
    "Name": "A",
    "Age": "A"
  },
  {
    "SID": "A",
    "Name": "A",
    "Age": "A"
  }
]`

And I am trying to insert data like this which returns an error without updating the db,
`this.dbService
                .bulkAdd('students', [studentsList])
                .subscribe((storeData) => {
                  console.log('stored');
                });`
When I check the dbStore, I see all the records are inserted in a single row and when I click on single column name such as Name or Age, I dont see values.
But when I try your example on bulkAdd, it inserts and show values on respective columns.

Am I doing something wrong here?
Please help

**Comment by aparzi** [comment]
Hi @DamForums,
this problem will be investigated as soon as possible.

**Comment by gbharathkumar** [comment]
Hi @DamForums ,

The reason for all the array items getting inserted into the first row might be due to the way you pass the values. You are passing an array inside another one 

this.dbService .bulkAdd('students', [studentsList]) .subscribe((storeData) => { console.log('stored'); });

Here instead of [studentslist] it should be simply studentslist as second parameter as passing an array the way you pass would create new array and place your framed array as first item.

So it should be this way 
this.dbService .bulkAdd('students', studentsList) .subscribe((storeData) => { console.log('stored'); });


Hope that helps.

**Comment by aparzi** [comment]
Hi @DamForums,
excellent observation, the cause also could be this. Also, consider that a pull request is open that fixes a problem related to performance and in general to the bulkadd function. The change is pending approval.

**Comment by aparzi** [comment]
Hi @DamForums,
a fix has been applied to the bulkAdd method could you try again?

Thank you
