### ISSUE TITLE
Version 17 imports seem broken

### ISSUE THREAD

**Issue by slubowsky** [assuncaocharles/ngx-indexed-db#382]
Have code compiling and working with version 16. After attempting to update to 17, Angular code doesn't compile...

```
Application bundle generation failed. [42.063 seconds]

X [ERROR] TS2305: Module '"ngx-indexed-db"' has no exported member 'NgxIndexedDBModule'. [plugin angular-compiler]

    src/app/app-provider.config.ts:38:9:
      38 │ import { NgxIndexedDBModule } from 'ngx-indexed-db';
         ╵          ~~~~~~~~~~~~~~~~~~


X [ERROR] TS2305: Module '"ngx-indexed-db"' has no exported member 'NgxIndexedDBService'. [plugin angular-compiler]

    src/app/shared/file-system-access/file-system-access.service.ts:4:9:
      4 │ import { NgxIndexedDBService } from 'ngx-indexed-db';
        ╵          ~~~~~~~~~~~~~~~~~~~


X [ERROR] TS-992003: No suitable injection token for parameter 'dbService' of class 'FileSystemAccessService'.
  Consider using the @Inject decorator to specify an injection token. [plugin angular-compiler]

    src/app/shared/file-system-access/file-system-access.service.ts:20:22:
      20 │   constructor(private dbService: NgxIndexedDBService,
         ╵                       ~~~~~~~~~

  This type does not have a value, so it cannot be used as injection token.

    src/app/shared/file-system-access/file-system-access.service.ts:20:33:
      20 │   constructor(private dbService: NgxIndexedDBService,
```

**Comment by assuncaocharles** [comment]
@aparzi can you take a look?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
maybe tonight, I don't know in the next few days.  could we think about a rollback in this case?

**Comment by aparzi** [comment]
Hi @assuncaocharles,
I did some checking and it seems to be "only" a problem with how the library was published. Because the entire dist folder was published and not its contents.
I bring you two screen shots (correct and incorrect). I recommend republishing as 17.0.1 and labeling 17.0.0 as incorrect if possible.

**Wrong:**
![image](https://github.com/assuncaocharles/ngx-indexed-db/assets/16490359/48e38f47-66d5-4d74-b353-517a7fbc24e9)

**Correct:**
![image](https://github.com/assuncaocharles/ngx-indexed-db/assets/16490359/d6ee7e92-ee19-45c6-9b3e-1b0546f46f28)

**Comment by aparzi** [comment]
Hi @slubowsky,
a new version (17.0.3) has been released with the fix.  please update and let us know.  If everything is ok, I ask you to kindly close the issue.  Thank you.

**Comment by slubowsky** [comment]
@aparzi Yes. New version seems to be working. Thank you!
